name: github_env

on:
  push:
    branches:
      - '**'

jobs:
  echo_multiline:
    runs-on: ubuntu-latest
    steps:
    - name: Echo output
      shell: bash
      run: |
        echo "hoge" > out.txt
        echo "fuga" >> out.txt
        echo 'MESSAGE<<EOF' >> $GITHUB_ENV
        echo "A" >> $GITHUB_ENV
        echo "B" >> $GITHUB_ENV
        echo "C" >> $GITHUB_ENV
        cat out.txt >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - run: echo "${{ env.MESSAGE }}"
